language: python
python:
  - "3.6"
  - "nightly"

# Coverage
before_install:
  - pip install pytest-cov
  - cd python

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest -v --cov=maths